services:
  - type: web
    name: shoppie
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: CORS_METHODS
        value: "GET,POST,OPTIONS"
      - key: CORS_HEADERS
        value: "Content-Type,Authorization"
      - key: FLASK_ENV
        value: production
      - key: PROXY_CHAT_URL
        value: "https://shoppie-mlw5.onrender.com/proxy/chat" 